blog/urls.py
from django.urls import path
from blog.views import ContactView, BlogCreateView, BlogListView, BlogUpdateView, BlogDetailView, BlogDeleteView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('contacts/', ContactView.as_view(), name='contacts'),
    ]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('medical_services.urls')),
    path('users/', include('users.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medical_services/urls.py
from django.urls import path
from medical_services.views import (home, CategoryListView, CategoryCreateView, ServiceListView,
                                    CategoryServiceListView, ServiceCreateView, ServiceDetailView, ServiceUpdateView,
                                    ServiceDeleteView, CategoryUpdateView, CategoryDeleteView, ContactView,
                                    ServiceCartView, AddToCartView, remove_service, clear_service)

app_name = 'medical_services'

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', ContactView.as_view(), name='contacts'),
    path('add_to_cart/<int:pk>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove_service/<int:service_id>/', remove_service, name='remove_service'),
    path('clear_service/', clear_service, name='clear_service'),


    path('category_create/', CategoryCreateView.as_view(), name='category_create'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),
    path('category_update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category_delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

    path('service_create/', ServiceCreateView.as_view(), name='service_create'),
    path('service_list/', ServiceListView.as_view(), name='service_list'),
    path('service_list/<int:pk>/', CategoryServiceListView.as_view(), name='service_list'),
    path('service_detail/<int:pk>/', ServiceDetailView.as_view(), name='service_detail'),
    path('service_update/<int:pk>/', ServiceUpdateView.as_view(), name='service_update'),
    path('service_delete/<int:pk>/', ServiceDeleteView.as_view(), name='service_delete'),
    path('service_cart/', ServiceCartView.as_view(), name='service_cart'),
    ]

blog/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Blog(models.Model):
    blog_title = models.CharField(max_length=100, verbose_name='Название блога')
    blog_description = models.TextField(max_length=200, verbose_name='Описание блога')
    blog_image = models.ImageField(upload_to='blog_images', verbose_name='Изображение блога', **NULLABLE)
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания блога')

    is_published = models.BooleanField(default=True, verbose_name='Опубликован')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)

    def __str__(self):
        return f'{self.blog_title} - {self.blog_description}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView
from pytils.translit import slugify

from blog.models import Blog


class ContactView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'blog/contacts.html')


class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Blog
    fields = ('blog_title', 'blog_description', 'blog_image', 'is_published',)
    permission_required = ('blog.add_blog',)
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):    # Задание 3: выводить в список статей только те, которые имеют положительный признак публикации
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.blog_title)    # В консоли нужно установить модуль pytils
            new_blog.save()

        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title', 'blog_description', 'blog_image', 'is_published',)
    permission_required = ('blog.change_blog',)

    def form_valid(self, form):
        if form.is_valid():
            blog = form.save()
            blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:view', args=[self.kwargs.get('pk')])


class BlogListView(LoginRequiredMixin, ListView):
    model = Blog

    template_name = 'blog_list.html'

    def get_queryset(self, *args, **kwargs):    # Задание 3: выводить в список статей только c положительным признаком публикации
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get(self, request, pk, **kwargs):
        blog = self.get_object()
        context = {
            'object_list': Blog.objects.filter(pk=pk),
        }
        return render(request, 'blog/blog_detail.html', context)

    def get_object(self, queryset=None):    # Задание 3: при открытии отдельной статьи увеличивать счетчик просмотров;
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Blog
    permission_required = ('blog.delete_blog',)
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Album example for Bootstrap</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

{% include 'medical_services/menu.html' %}

<main role="main">

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {% block content %}

                {% endblock %}

            </div>
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Наверх</a>
        </p>
        <p>  © ПеКоТо 2023 - {% now "Y" %}</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends "blog/base.html" %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить блог "{{ object.blog_title }}"?</p>
                    <button type="submit" class="btn btn-success">Подтвердить</button>
                    <a href="{% url 'blog:blog_list' %}" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% load my_tags_blog %}
{% block content %}
{% for object in object_list %}
<div class="col-md-6">
    <div class="card mb-4 box-shadow">
        <img class="card-img-top"
             src="{{ object.blog_image | blog_image }}" height="300"
             alt="Card image cap">
        <div class="card-body">
            <p class="card-text">
                {% if object.is_published %}
                <b>Блог: "{{ object.blog_title|title }}"</b> ({{ object.slug }})
                {% else %}
                <span class="text-muted"><b>Блог: "{{ object.blog_title|title }}"</b> ({{ object.slug }})</span>
                {% endif %}
            </p>
            <div class="card_body">

                <p>
                    {{ object.blog_description }}
                </p>
            </div>

            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <form>
                    <a href="{% url 'blog:blog_list' %}" class="btn btn-sm btn-dark">Вернуться</a>
                        {% if perms.blog.change_blog %}
                    <a href="{% url 'blog:edit' object.pk %}" class="btn btn-sm btn-dark">Редактировать</a>
                        {% endif %}
                        {% if perms.blog.delete_blog %}
                    <a href="{% url 'blog:delete' object.pk %}" class="btn btn-sm btn-danger">Удалить</a>
                        {% endif %}
                </form>
                </div>
                <div class="card_footer">
                    Просмотры: {{ object.views_count }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

blog/templates/blog/blog_form.html
{% extends "blog/base.html" %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-dark">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Cоздать
                        {% endif %}
                    </button>
                    <input type="button" class="btn btn-dark" value="Назад" onclick="history.back()">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% load my_tags_blog %}
{% block content %}
<div class="col-12 mb-5">
    {% if perms.blog.add_blog %}
    <a class="btn btn-dark" href="{% url 'blog:create' %}">Добавить новость</a>
    {% endif %}
</div>
{% for object in object_list %}
<div class="col-md-6">
    <div class="card mb-4 box-shadow">
        <img class="card-img-top"
             src="{{ object.blog_image | blog_image }}" height="300"
             alt="Card image cap">
        <div style="height: 170px;" class="card-body">
            <p class="card-text">
                {% if object.is_published %}
                <b>Блог: "{{ object.blog_title|title }}"</b>
                {% else %}
                <span class="text-muted"><b>Блог: "{{ object.blog_title|title }}"</b></span>
                {% endif %}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <form>
                    <a href="{% url 'blog:view' object.pk %}"
                       class="btn btn-sm btn-dark">Подробнее</a>
                    {% if perms.blog.change_blog %}
                    <a href="{% url 'blog:edit' object.pk %}"
                       class="btn btn-sm btn-dark">Редактировать</a>
                    {% endif %}
                    {% if perms.blog.delete_blog %}
                    <a href="{% url 'blog:delete' object.pk %}"
                       class="btn btn-sm btn-danger">Удалить</a>
                    {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

blog/templates/blog/menu.html
{% load static %}
{% load my_tags_users %}
<header>
    <div class="navbar navbar-dark bg-info shadow-sm">
        <div class="container d-flex justify-content-between">
            <a href="{% url 'medical_services:home' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2"
                     viewBox="0 0 24 24" focusable="false">
                    <img src="{% static 'logo.png' %}" width="100" height="93" alt="Logo"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
            </a>
            <h4 class="text-light" style="text-align: center;">Медицинские исследования</h4>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="col-sm-8 col-md-7 py-4 d-flex">
                {% if user.is_authenticated %}
                <div class="d-flex align-items-center">
                {% if user.avatar %}
                    <img class="card-img-top rounded-circle"
                         src="{{ user.avatar.url }}"
                         style="width: 100px; height: 100px; object-fit: cover;"
                         alt="User Avatar">
                {% endif %}
                <div style="margin-left: 15px;">
                    {% if user.first_name %}
                        <h4 class="text-light mb-0">Аккаунт: {{ user.first_name }} {{ user.last_name }}</h4>
                    {% else %}
                        <h4 class="text-light mb-0">Аккаунт: {{ user.email }}</h4>
                    {% endif %}
                </div>
            </div>
                {% endif %}
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4 d-flex">
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'medical_services:home' %}"><u>Главная</u></a>
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'medical_services:category_list' %}"><u>Категории</u></a>
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'medical_services:service_list' %}"><u>Услуги</u></a>
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'medical_services:contacts' %}"><u>Контакты</u></a>
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'blog:blog_list' %}"><u>Блог</u></a>
                    {% if user.is_authenticated %}
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'users:profile' %}"><u>Профиль</u></a>
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'medical_services:service_cart' %}"><u>Корзина</u></a>
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'users:logout' %}"><u>Выход</u></a>
                    {% else %}
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'users:login' %}"><u>Вход</u></a>
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'users:register' %}"><u>Регистрация</u></a>
                    {% endif %}
                    {% if user.is_superuser or user.is_staff %}
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="/admin/"><u>Админка</u></a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</header>