blog/urls.py
from django.urls import path
from blog.views import ContactView, BlogCreateView, BlogListView, BlogUpdateView, BlogDetailView, BlogDeleteView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('contacts/', ContactView.as_view(), name='contacts'),
    ]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('medical_services.urls')),
    path('users/', include('users.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medical_services/urls.py
from django.urls import path
from medical_services.views import (home, CategoryListView, CategoryCreateView, ServiceListView,
                                    CategoryServiceListView, ServiceCreateView, ServiceDetailView, ServiceUpdateView,
                                    ServiceDeleteView, CategoryUpdateView, CategoryDeleteView, ContactView,
                                    ServiceCartView, AddToCartView, remove_service, clear_service)

app_name = 'medical_services'

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', ContactView.as_view(), name='contacts'),
    path('add_to_cart/<int:pk>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove_service/<int:service_id>/', remove_service, name='remove_service'),
    path('clear_service/', clear_service, name='clear_service'),


    path('category_create/', CategoryCreateView.as_view(), name='category_create'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),
    path('category_update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category_delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

    path('service_create/', ServiceCreateView.as_view(), name='service_create'),
    path('service_list/', ServiceListView.as_view(), name='service_list'),
    path('service_list/<int:pk>/', CategoryServiceListView.as_view(), name='service_list'),
    path('service_detail/<int:pk>/', ServiceDetailView.as_view(), name='service_detail'),
    path('service_update/<int:pk>/', ServiceUpdateView.as_view(), name='service_update'),
    path('service_delete/<int:pk>/', ServiceDeleteView.as_view(), name='service_delete'),
    path('service_cart/', ServiceCartView.as_view(), name='service_cart'),
    ]

medical_services/models.py
from django.conf import settings
from django.db import models

# Create your models here.
NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    """Модель категории."""
    category_title = models.CharField(max_length=100, verbose_name='название')
    category_description = models.TextField(verbose_name='описание')
    category_image = models.ImageField(upload_to='categories/', verbose_name='изображение', **NULLABLE)

    def __str__(self):
        return self.category_title

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"


class Service(models.Model):
    """Модель услуги."""
    services_title = models.CharField(max_length=100, verbose_name='название')
    services_description = models.TextField(verbose_name='описание')
    price = models.PositiveIntegerField(verbose_name='цена')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='категория')
    deadline = models.CharField(max_length=100, verbose_name='срок выполнения')

    def __str__(self):
        return self.services_title

    class Meta:
        verbose_name = "услуга"
        verbose_name_plural = "услуги"


class Cart(models.Model):
    """Модель корзины."""
    client = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='клиент')
    services = models.ManyToManyField('Service', verbose_name='услуги')
    date = models.DateTimeField(verbose_name='дата и время', **NULLABLE)

    def __str__(self):
        return f'{self.client} - {self.services}'

    class Meta:
        verbose_name = "корзина"
        verbose_name_plural = "корзины"

medical_services/forms.py
from django import forms
from medical_services.models import Service, Category, Cart


class CategoryForm(forms.ModelForm):
    """Форма создания категорий медицинских услуг."""
    class Meta:
        model = Category
        fields = ("category_title", "category_description", "category_image",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ServicesForm(forms.ModelForm):
    """Форма создания услуги."""
    class Meta:
        model = Service
        fields = ("services_title", "services_description", "category", "price", "deadline",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CartForm(forms.ModelForm):
    """Форма создания корзины."""
    class Meta:
        model = Cart
        fields = ("services", "date", "client",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

medical_services/views.py
import json
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseForbidden, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.views import View
from django.views.generic import ListView, DeleteView, DetailView, CreateView, UpdateView
from django.urls import reverse
from config import settings
from medical_services.forms import CategoryForm, ServicesForm
from medical_services.models import Category, Service, Cart

from django.urls import reverse_lazy


# Классы категории
class CategoryCreateView(CreateView, PermissionRequiredMixin):
    """Класс создания категорий медицинских услуг."""
    model = Category
    form_class = CategoryForm
    permission_required = 'medical_services.add_category'
    success_url = reverse_lazy("medical_services:category_list")

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm('medical_services.add_category'):
            return HttpResponseForbidden("У вас нет доступа")
        return super().dispatch(request, *args, **kwargs)


class CategoryListView(ListView):
    """Класс отображения списка категорий медицинских услуг."""
    model = Category


class CategoryUpdateView(UpdateView, PermissionRequiredMixin):
    """Класс обновления категорий медицинских услуг."""
    model = Category
    form_class = CategoryForm
    permission_required = 'medical_services.change_category'
    success_url = reverse_lazy("medical_services:category_list")

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm('medical_services.change_category'):
            return HttpResponseForbidden("У вас нет доступа")
        return super().dispatch(request, *args, **kwargs)


class CategoryDeleteView(DeleteView, PermissionRequiredMixin):
    """Класс удаления категорий медицинских услуг."""
    model = Category
    success_url = reverse_lazy("medical_services:category_list")
    permission_required = 'medical_services.delete_category'
    template_name = "medical_services/category_confirm_delete.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = self.get_object().category_title
        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm('medical_services.delete_category'):
            return HttpResponseForbidden("У вас нет доступа")
        return super().dispatch(request, *args, **kwargs)


class CategoryServiceListView(ListView):
    """Класс отображения списка услуг по категориям медицинских услуг."""
    model = Service

    def get_queryset(self):
        category_pk = self.kwargs['pk']
        return Service.objects.filter(category_id=category_pk)


# Классы услуг
class ServiceCreateView(CreateView, PermissionRequiredMixin):
    """Класс создания услуг."""
    model = Service
    form_class = ServicesForm
    permission_required = 'medical_services.add_service'
    success_url = reverse_lazy("medical_services:service_list")

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm('medical_services.add_service'):
            return HttpResponseForbidden("У вас нет доступа")
        return super().dispatch(request, *args, **kwargs)


class ServiceListView(ListView):
    """Класс отображения списка услуг."""
    model = Service


class ServiceDetailView(DetailView):
    """Класс отображения детальной информации об услуге."""
    model = Service

    def get(self, request, pk):
        product = Service.objects.get(pk=pk)
        context = {
            'object_list': Service.objects.filter(id=pk),
        }
        return render(request, 'medical_services/service_detail.html', context)


class ServiceUpdateView(UpdateView, PermissionRequiredMixin):
    """Класс обновления услуг."""
    model = Service
    form_class = ServicesForm
    permission_required = 'medical_services.change_service'
    success_url = reverse_lazy("medical_services:service_list")

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm('medical_services.change_service'):
            return HttpResponseForbidden("У вас нет доступа")
        return super().dispatch(request, *args, **kwargs)


class ServiceDeleteView(DeleteView, PermissionRequiredMixin):
    """Класс удаления услуг."""
    model = Service
    success_url = reverse_lazy("medical_services:service_list")
    permission_required = 'medical_services.delete_service'
    template_name = "medical_services/service_confirm_delete.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = self.get_object().services_title
        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm('medical_services.delete_service'):
            return HttpResponseForbidden("У вас нет доступа")
        return super().dispatch(request, *args, **kwargs)


class ContactView(View):
    """Класс обработки формы обратной связи."""

    def get(self, request):
        return render(request, 'medical_services/contacts.html')

    def post(self, request):
        if request.method == 'POST':
            name = request.POST.get('name')
            phone = request.POST.get('phone')
            message = request.POST.get('message')

            # Логика для отправки письма администратору
            subject = 'Обращение от посетителя сайта'
            admin_message = f'Имя: {name}\nТелефон: {phone}\nСообщение: {message}'
            send_mail(
                subject=subject,
                message=admin_message,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[settings.EMAIL_HOST_USER],  # Замените на реальный адрес администратора
            )

            success_message = 'Ваше сообщение успешно отправлено. Мы свяжемся с вами в ближайшее время.'
            context = {'success_message': success_message}
            return render(request, 'medical_services/contacts_success.html', context)


class ServiceCartView(View):
    """Класс отображения корзины услуг."""
    model = Cart

    def get(self, request):
        # Получаем объект корзины для текущего пользователя
        cart = Cart.objects.filter(client=request.user).first()

        # Получаем количество услуг в корзине
        services_count = cart.services.count() if cart else 0

        # Получаем список услуг в корзине
        services = cart.services.all() if cart else []

        # Получаем данные о клиенте
        client = cart.client if cart else None

        # Получаем сумму покупок услуг в корзине
        total_price = sum(service.price for service in services)

        # Обновляем контекст
        context = {
            'services_count': services_count,
            'services': services,
            'total_price': total_price,
            'client': client
        }
        return render(request, 'medical_services/shopping_cart.html', context)

    def post(self, request):
        cart = Cart.objects.filter(client=request.user).first()
        if cart:
            services = cart.services.all()
            total_price = sum(service.price for service in services)

            # Логика для отправки письма администратору
            context = {'services': services, 'total_price': total_price, 'user': request.user}
            admin_message = render_to_string('medical_services/admin_cart_email.html', context)
            send_mail(
                subject='Новый заказ в медицинской клинике',
                message='Новый заказ в медицинской клинике',
                html_message=admin_message,  # Отправка HTML-сообщения
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[settings.EMAIL_HOST_USER],  # Замените на реальный адрес администратора
            )

            # Логика для отправки письма пользователю
            user_message = render_to_string('medical_services/cart_email.html', context)
            send_mail(
                subject='Оформление заказа в медицинской клинике',
                message='Оформление заказа в медицинской клинике',
                html_message=user_message,  # Отправка HTML-сообщения
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[request.user.email],
            )

            cart.services.clear()  # Очистка корзины

            success_message = 'Ваше сообщение успешно отправлено. Мы свяжемся с вами в ближайшее время.'
            context = {'success_message': success_message}
            return render(request, 'medical_services/contacts_success.html', context)
        else:
            return HttpResponse('Ошибка отправки письма о заказе на вашу почту')


class AddToCartView(View):
    """Класс добавления услуги в корзину."""
    def post(self, request, pk):
        json_data = json.loads(request.body)
        service_id = json_data.get('service_id')
        service = Service.objects.get(pk=service_id)

        # Получите объект корзины текущего пользователя или создайте новый
        cart, created = Cart.objects.get_or_create(client=request.user)

        # Добавление услуги в корзину
        cart.services.add(service)

        return JsonResponse({'message': 'Услуга успешно добавлена в корзину.'})


def home(request):
    """Функция отображения главной страницы."""
    return render(request, 'medical_services/home.html')

medical_services/templates/medical_services/admin_cart_email.html
<h2>Новый заказ на сайте</h2>
<p>Пользователь {{ user.email }} оформил заказ на сумму {{ total_price }} рублей.</p>
<ul>
    {% for service in services %}
        <li>{{ service.services_title }} - {{ service.price }} ₽</li>
    {% endfor %}
</ul>

medical_services/templates/medical_services/category_list.html
{% extends 'medical_services/base.html' %}
{% load my_tags_medical_services %}
{% block content %}
<style>
    .details-summary {
        list-style: none;
        cursor: pointer;
        background-color: #fff;
        color: #000;
        padding: 8px 16px;
        border: 1px solid #ffffff;
        border-radius: 4px;
        display: inline-block;
        transition: background-color 0.3s, color 0.3s;
        margin-bottom: 5px;
    }

    .details-summary:hover {
        background-color: #ffffff;
        border-color: #666666;
    }

    .details-summary:focus {
        outline: none;
    }
</style>
<div class="col-12 mb-5">
    {% if user.is_staff or user.is_superuser %}
    <a class="btn btn-dark" href="{% url 'medical_services:category_create' %}">Добавить категорию</a>
    {% endif %}
</div>
{% for object in object_list %}
<div class="col-md-6">
    <div class="card mb-4 box-shadow">
        <details>
        <summary class="details-summary">
                <img class="card-img-top"
                     src="{{ object.category_image | category_image }}" width="300" height="225"
                     alt="Card image cap">
                <b>Категория:</b> {{ object.category_title | slice:":100" }}

            </summary>
        <div class="card-body">
            <p class="card-text">
                <b>Описание:</b> {{ object.category_description | slice:":100" }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <form>
                        <a href="{% url 'medical_services:service_list' pk=object.id %}" class="btn btn-sm btn-dark">Посмотреть</a>
                        {% if user.is_staff or user.is_superuser %}
                        <a href="{% url 'medical_services:category_update' object.pk %}" class="btn btn-sm btn-dark">Изменить</a>
                        <a href="{% url 'medical_services:category_delete' object.pk %}" class="btn btn-sm btn-danger">Удалить</a>
                        {% endif %}
                    </form>
                </div>
                <small class="text-muted"></small>
            </div>
        </div>
        </details>
    </div>
</div>
{% endfor %}
{%  endblock %}

medical_services/templates/medical_services/contacts_success.html
{% extends "medical_services/base.html" %}

{% block content %}
<div class="container">
    <div class="py-5 text-center">
        <h2>Успех!</h2>
        <p>{{ success_message }}</p>
    </div>
</div>
{% endblock %}

medical_services/templates/medical_services/menu.html
{% load static %}
{% load my_tags_users %}
<header>
    <div class="navbar navbar-dark bg-info shadow-sm">
        <div class="container d-flex justify-content-between">
            <a href="{% url 'medical_services:home' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2"
                     viewBox="0 0 24 24" focusable="false">
                    <img src="{% static 'logo.png' %}" width="100" height="93" alt="Logo"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
            </a>
            <h4 class="text-light" style="text-align: center;">Медицинские исследования</h4>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="col-sm-8 col-md-7 py-4 d-flex">
                {% if user.is_authenticated %}
                <div class="d-flex align-items-center">
                {% if user.avatar %}
                    <img class="card-img-top rounded-circle"
                         src="{{ user.avatar.url }}"
                         style="width: 100px; height: 100px; object-fit: cover;"
                         alt="User Avatar">
                {% endif %}
                <div style="margin-left: 15px;">
                    {% if user.first_name %}
                        <h4 class="text-light mb-0">{{ user.first_name }} {{ user.last_name }}</h4>
                    {% else %}
                        <h4 class="text-light mb-0">{{ user.email }}</h4>
                    {% endif %}
                </div>
            </div>
                {% endif %}
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4 d-flex">
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'medical_services:home' %}"><u>Главная</u></a>
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'medical_services:category_list' %}"><u>Категории</u></a>
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'medical_services:service_list' %}"><u>Услуги</u></a>
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'medical_services:contacts' %}"><u>Контакты</u></a>
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'blog:blog_list' %}"><u>Новости</u></a>
                    {% if user.is_authenticated %}
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'users:profile' %}"><u>Профиль</u></a>
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'medical_services:service_cart' %}"><u>Корзина</u></a>
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'users:logout' %}"><u>Выход</u></a>
                    {% else %}
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'users:login' %}"><u>Вход</u></a>
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="{% url 'users:register' %}"><u>Регистрация</u></a>
                    {% endif %}
                    {% if user.is_superuser or user.is_staff %}
                    <a class="nav-link d-flex align-items-center text-light mx-2"
                       href="/admin/"><u>Админка</u></a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</header>

medical_services/templates/medical_services/service_list.html
{% extends 'medical_services/base.html' %}
{% load my_tags_medical_services %}
{% block content %}
<style>
    .card-body {
        overflow: hidden;
    }

    .card-text {
        overflow: hidden;
        max-height: 30px;
        transition: max-height 0.5s;
    }

    .card-body:hover .card-text {
        max-height: 200px;
        transition: max-height 0.5s;
    }
    .no-border-radius {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
    }
</style>

<div class="col-12 mb-5">
    {% if user.is_staff or user.is_superuser %}
    <a class="btn btn-dark" href="{% url 'medical_services:service_create' %}">Добавить услугу</a>
    {% endif %}
    <a class="btn btn-dark" href="{% url 'medical_services:service_cart' %}">Корзина</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">

            <p class="card-text">
                <b>Название:</b> {{ object.services_title | slice:":100" }}
            </p>
            <div class="card-text">
                <p class="card-text">
                    <b>Категория:</b> {{ object.category | slice:":100" }}
                </p>
                <p>
                    <b>Описание:</b> {{ object.services_description | slice:":100" }}
                </p>
                <p>
                    <b>Цена:</b> {{ object.price | slice:":100" }} рублей
                </p>
                <p>
                    <b>Срок выполнения:</b> {{ object.deadline| slice:":100" }}
                </p>
            </div>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <form>

                        <a href="{% url 'medical_services:service_detail' object.pk %}" class="btn btn-sm btn-dark">Посмотреть</a>

                        {% if user.is_staff or user.is_superuser %}
                        <a href="{% url 'medical_services:service_update' object.pk %}" class="btn btn-sm btn-dark">Изменить</a>
                        <a href="{% url 'medical_services:service_delete' object.pk %}" class="btn btn-sm btn-danger">Удалить</a>
                        {% endif %}
                    </form>
                </div>
                <small class="text-muted"></small>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

medical_services/templates/medical_services/shopping_cart.html
{% extends 'medical_services/base.html' %}

{% block content %}

<div class="container">
    <div class="py-5 text-center">
        <h2>Корзина</h2>
        <p class="lead">Проверьте ваш заказ услуг.<br>После нажатия кнопки "Оплатить" вам на почту придет письмо с
            указанием выбранных вами услуг.</p>
    </div>

    <div class="row">
        <div class="col-md-6 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="mb-3">Ваш заказ</span>
                <span class="badge badge-secondary badge-pill">{{ services_count }}</span>
            </h4>

            <ul class="list-group mb-3">
                {% for service in services %}
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">{{ service.services_title | slice:":50" }}</h6>
                        <small class="text-muted">Срок выполнения: {{ service.deadline }}</small>
                    </div>
                    <span class="text-muted">{{ service.price }} ₽</span>
                    <form method="post" action="{% url 'medical_services:remove_service' service.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="service_id" value="{{ service.id }}">
                        <button type="submit" class="btn btn-link text-danger">Удалить</button>
                    </form>
                </li>
                {% endfor %}
                <li class="list-group-item d-flex justify-content-between">
                    <span><strong>Итого</strong></span>
                    <strong>{{ total_price }} ₽</strong>
                </li>
            </ul>
            <form method="post" action="{% url 'medical_services:clear_service' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Очистить</button>
            </form>
        </div>
        <div class="col-md-6 order-md-1">
            <h4 class="mb-3">Данные клиента</h4>
            <form class="needs-validation" novalidate>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="firstName">First name</label>
                        <input type="text" class="form-control" id="firstName"
                               placeholder="{% if client.first_name %}{{ client.first_name }}{% endif %}"
                               value="{% if client.first_name %}{{ client.first_name }}{% endif %}" required>
                        <div class="invalid-feedback">
                            Valid first name is required.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName">Last name</label>
                        <input type="text" class="form-control" id="lastName" placeholder=""
                               value="{% if client.last_name %}{{ client.last_name }}{% endif %}" required>
                        <div class="invalid-feedback">
                            Valid last name is required.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName">Patronymic</label>
                        <input type="text" class="form-control" id="patronymic" placeholder=""
                               value="{% if client.patronymic %}{{ client.patronymic }}{% endif %}" required>
                        <div class="invalid-feedback">
                            Valid patronymic is required.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName">Phone</label>
                        <input type="text" class="form-control" id="phone" placeholder=""
                               value="{% if client.phone %}{{ client.phone }}{% endif %}" required>
                        <div class="invalid-feedback">
                            Valid phone is required.
                        </div>
                    </div>
                </div>

                <div class="mb-3">
                    <label for="email">Email</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">@</span>
                        </div>
                        <input type="text" class="form-control" id="email" placeholder=""
                               value="{% if client.email %}{{ client.email }}{% endif %}" required>
                        <div class="invalid-feedback" style="width: 100%;">
                            Your username is required.
                        </div>
                    </div>
                </div>
                <hr class="mb-4">

                <div class="mb-3">
                    <label for="date">Выберите дату приема</label>
                    <div class="input-group">
                        <input type="date" class="form-control" id="date" name="date" value="{{ date }}" required>
                        <div class="invalid-feedback" style="width: 100%;">
                            Выберите дату приема.
                        </div>
                    </div>
                </div>

                <div class="mb-3">
                    <label for="time">Выберите время приема</label>
                    <div class="input-group">
                        <input type="time" class="form-control" id="time" name="time" value="{{ time }}" required>
                        <div class="invalid-feedback" style="width: 100%;">
                            Выберите время приема.
                        </div>
                    </div>
                </div>

            </form>
            <form method="post">
                {% csrf_token %}
                <button class="btn btn-dark btn-lg btn-block" type="submit">Заказать</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}